Bump Alizer to fix potential panic when analyzing large projects (#6926)
* Bump Alizer to the latest commit at this time [1]

Amongst other things, this fixes an issue when analyzing large projects,
by preventing potential panics when trying to detect application ports.

[1] https://github.com/redhat-developer/alizer/commit/14114f066cef8c0f9fea66754f2337db01edf75a

* Downgrade and pin the versions of 'sigs.k8s.io/controller-runtime' and 'k8s.io/*' to the previous versions we had

Bumping Alizer bumped these packages to upper versions,
which seems to cause build errors due to Service Binding Operator
libraries not compatible with those new versions.
See the error below.

Since we don't want to update SBO libraries at this time
(as SBO is currently in maintenance mode only),
this makes sure we are using the versions it builds against.

Build error for reference:
```
go install -mod=vendor -ldflags="-X github.com/redhat-developer/odo/pkg/version.GITCOMMIT=cb9c13900" ./cmd/odo/
# github.com/redhat-developer/service-binding-operator/apis/spec/v1alpha3
vendor/github.com/redhat-developer/service-binding-operator/apis/spec/v1alpha3/servicebinding_webhook.go:44:27: cannot use &ServiceBinding{} (value of type *ServiceBinding) as type admission.Validator in variable declaration:
        *ServiceBinding does not implement admission.Validator (wrong type for ValidateCreate method)
                have ValidateCreate() error
                want ValidateCreate() (warnings admission.Warnings, err error)
# github.com/redhat-developer/service-binding-operator/apis/binding/v1alpha1
vendor/github.com/redhat-developer/service-binding-operator/apis/binding/v1alpha1/servicebinding_webhook.go:37:27: cannot use &ServiceBinding{} (value of type *ServiceBinding) as type admission.Validator in variable declaration:
        *ServiceBinding does not implement admission.Validator (wrong type for ValidateCreate method)
                have ValidateCreate() error
                want ValidateCreate() (warnings admission.Warnings, err error)
make: *** [Makefile:90: install] Error 2
```

* Fix expected output in doc automation tests