Fix flakey tests
**What type of PR is this?**

/kind flake

**What does does this PR do / why we need it**:

Why? Because we need 1.2.0 release out.

Two things:

 -  We have to disable the URL tests since they are failing internally
 on our CI systems:

```sh
--- FAIL: TestUnzip (0.02s)
    --- FAIL: TestUnzip/Case_1:_Valid_zip_ (0.02s)
        util_test.go:1459: /tmp/unzip228137821
        util_test.go:1464: Error downloading zip: Get https://github.com/che-samples/web-nodejs-sample/archive/master.zip: dial tcp: lookup github.com on [::1]:53: read udp [::1]:57816->[::1]:53: read: connection refused
        util_test.go:1468: Error unzipping: zip: not a valid zip file
        util_test.go:1473: Expected file package.json does not exist in directory after unzipping
        util_test.go:1473: Expected file package-lock.json does not exist in directory after unzipping
        util_test.go:1473: Expected file app does not exist in directory after unzipping
        util_test.go:1473: Expected file .gitignore does not exist in directory after unzipping
        util_test.go:1473: Expected file LICENSE does not exist in directory after unzipping
        util_test.go:1473: Expected file README.md does not exist in directory after unzipping
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf6c63f]
goroutine 248 [running]:
testing.tRunner.func1(0xc0003b9a00)
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/testing/testing.go:830 +0x69d
panic(0x10560e0, 0x1a014b0)
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/panic.go:522 +0x1b5
github.com/openshift/odo/pkg/util.GetGitHubZipURL(0x115ba74, 0x26, 0x732c09a, 0x732c09a00380c01, 0x5ea739d4, 0xc000332760)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/util/util.go:796 +0x43f
github.com/openshift/odo/pkg/util.TestGetGitHubZipURL.func1(0xc0003b9a00)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/util/util_test.go:1605 +0x70
testing.tRunner(0xc0003b9a00, 0xc000380cf0)
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/testing/testing.go:865 +0x164
created by testing.(*T).Run
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/testing/testing.go:916 +0x65b
FAIL	github.com/openshift/odo/pkg/util	1.130s
==> 28217925:DEFAULT:root.log <==
DEBUG util.py:300:  Executing command: umount -n /mnt/build/mock/rhodo-1-rhel-7-build-5909115-3948169/root/dev/shm
DEBUG util.py:340:  Child returncode was: 0
DEBUG util.py:300:  Executing command: umount -n /mnt/build/mock/rhodo-1-rhel-7-build-5909115-3948169/root/dev/pts
DEBUG util.py:340:  Child returncode was: 0
DEBUG util.py:300:  Executing command: umount -n /mnt/build/mock/rhodo-1-rhel-7-build-5909115-3948169/root/proc/filesystems
DEBUG util.py:340:  Child returncode was: 0
DEBUG util.py:300:  Executing command: umount -n /mnt/build/mock/rhodo-1-rhel-7-build-5909115-3948169/root/sys
DEBUG util.py:340:  Child returncode was: 0
DEBUG util.py:300:  Executing command: umount -n /mnt/build/mock/rhodo-1-rhel-7-build-5909115-3948169/root/proc
DEBUG util.py:340:  Child returncode was: 0
DEBUG util.py:111:  kill orphans
```

Another is an issue with unzipping:

```sh
--- FAIL: TestUnzip (0.02s)
    --- FAIL: TestUnzip/Case_1:_Valid_zip_ (0.02s)
        util_test.go:1459: /tmp/unzip228137821
        util_test.go:1464: Error downloading zip: Get https://github.com/che-samples/web-nodejs-sample/archive/master.zip: dial tcp: lookup github.com on [::1]:53: read udp [::1]:57816->[::1]:53: read: connection refused
        util_test.go:1468: Error unzipping: zip: not a valid zip file
        util_test.go:1473: Expected file package.json does not exist in directory after unzipping
        util_test.go:1473: Expected file package-lock.json does not exist in directory after unzipping
        util_test.go:1473: Expected file app does not exist in directory after unzipping
        util_test.go:1473: Expected file .gitignore does not exist in directory after unzipping
        util_test.go:1473: Expected file LICENSE does not exist in directory after unzipping
        util_test.go:1473: Expected file README.md does not exist in directory after unzipping
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf6c63f]
goroutine 248 [running]:
testing.tRunner.func1(0xc0003b9a00)
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/testing/testing.go:830 +0x69d
panic(0x10560e0, 0x1a014b0)
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/panic.go:522 +0x1b5
github.com/openshift/odo/pkg/util.GetGitHubZipURL(0x115ba74, 0x26, 0x732c09a, 0x732c09a00380c01, 0x5ea739d4, 0xc000332760)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/util/util.go:796 +0x43f
github.com/openshift/odo/pkg/util.TestGetGitHubZipURL.func1(0xc0003b9a00)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/util/util_test.go:1605 +0x70
testing.tRunner(0xc0003b9a00, 0xc000380cf0)
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/testing/testing.go:865 +0x164
created by testing.(*T).Run
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/testing/testing.go:916 +0x65b
FAIL	github.com/openshift/odo/pkg/util	1.130s
```

**Which issue(s) this PR fixes**:

N/A

**How to test changes / Special notes to the reviewer**:

N/A

Signed-off-by: Charlie Drage <charlie@charliedrage.com>