Removes unnecessary newlines / outputs
Removes all unnecessary newlines that were added, this was caused by not
accounting `Sprintln` (which includes a newline...)

Changes:

```sh
github.com/redhat-developer/odo  remove-newline-error ✗                                                                                                                                                                                                                   1d ⚑  ⍉
▶ ./odo create nodejs
 ✗  unable to get current application

github.com/redhat-developer/odo  remove-newline-error ✗                                                                                                                                                                                                                   1d ⚑  ⍉
▶ make bin
go build -ldflags="-w -X github.com/redhat-developer/odo/pkg/odo/cli/version.GITCOMMIT=57603295" -o odo cmd/odo/odo.go

github.com/redhat-developer/odo  remove-newline-error ✗                                                                                                                                                                                                                    1d ⚑
▶ ./odo create nodejs
 ✗  unable to get current application
```

As well as for other output messages:

```sh
github.com/redhat-developer/odo  remove-newline-error ✗                                                                                                                                                                                                                    1d ✚
▶ ./odo push
Pushing changes to component: odo-nodejs-pjfp
 ✓  Waiting for pod to start
 ✓  Copying files to component
 ◐  Building component ✗  Unable to build files
+ set -eo pipefail
+ '[' '!' -z /opt/app-root/src ']'
+ '[' /tmp '!=' /opt/app-root/src ']'
+ '[' /opt/app-root/src '!=' /opt/app-root/src ']'
+ '[' -f /tmp/src/.s2i/bin/assemble ']'
+ '[' -n /usr/libexec/s2i ']'
+ rm -rf /opt/app-root/src/.git
+ /usr/libexec/s2i/assemble
---> Installing application source
---> Building your Node application from source
Current git config
url.https://github.com.insteadof=git@github.com:
url.https://.insteadof=ssh://
url.https://github.com.insteadof=ssh://git@github.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=git@github.com:cdrage/odo.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.namespace-components.remote=origin
branch.namespace-components.merge=refs/heads/namespace-components
branch.add-logs.remote=origin
branch.add-logs.merge=refs/heads/add-logs
remote.upstream.url=git@github.com:redhat-developer/odo.git
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
branch.gh-pages.remote=upstream
branch.gh-pages.merge=refs/heads/gh-pages
travis.slug=cdrage/odo
---> Installing dependencies
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module './package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at [eval]:1:13
    at Script.runInThisContext (vm.js:96:20)
    at Object.runInThisContext (vm.js:303:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at evalScript (internal/bootstrap/node.js:582:27)

 ✗  Building component
 ✗  command terminated with exit code 1
```